# Auto-generated by start_aero.bat — filters out psycopg2 from requirements
lines = [l for l in open('requirements.txt') if 'psycopg2' not in l.lower()]
open('_req_tmp.txt', 'w').writelines(lines)
print(f"  Filtered requirements: {len(lines)} packages")
